### ISSUE TITLE
BUG: stop worker and worker throw exception

### ISSUE THREAD

**Issue by ahkui** [roadrunner-php/issues#16]
### Exception Message:
```
Uncaught ErrorException: file_put_contents(): Write of 219 bytes failed with errno=32 Broken pipe in /var/www/service/vendor/spiral/roadrunner-worker/src/Internal/StdoutHandler.php:83
Stack trace:
#0 /var/www/service/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
roadrunner-php/worker#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
roadrunner-php/worker#2 /var/www/service/vendor/spiral/roadrunner-worker/src/Internal/StdoutHandler.php(83): file_put_contents()
roadrunner-php/worker#3 /var/www/service/vendor/symfony/http-foundation/Response.php(364): Spiral\RoadRunner\Internal\StdoutHandler::Spiral\RoadRunner\Internal\{closure}()
roadrunner-php/worker#4 /var/www/service/vendor/symfony/http-foundation/Response.php(377): Symfony\Component\HttpFoundation\Response->sendContent()
```

**Comment by roxblnfk** [comment]
Which package version did you use?

**Comment by ahkui** [comment]
use `laravel-octane`

1. composer create-project --prefer-dist laravel/laravel laravel-octane-test
2. composer require laravel/octane
3. php artisan octane:install --server=roadrunner
4. php artisan octane:start
5. use wrk simulate workload `wrk -t4 -c8 -d30m http://127.0.0.1:8000/api/test`
6. php artisan octane:stop
7. and exception is throw above

**Comment by roxblnfk** [comment]
Looks like octane issue
